# Generated by Django 3.1.4 on 2021-01-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioUrls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_url', models.CharField(default=None, max_length=200)),
                ('linkedin_url', models.CharField(default=None, max_length=100)),
                ('github_url', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
